// -------------------------------------------------------------
// 
// 
// Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Model base rate: 1e-06
// Target subsystem base rate: 1e-06
// 
// 
// Clock Enable  Sample Time
// -- -------------------------------------------------------------
// ce_out        4e-06
// -- -------------------------------------------------------------
// 
// 
// Output Signal                 Clock Enable  Sample Time
// -- -------------------------------------------------------------
// Output_rsvd                   ce_out        4e-06
// -- -------------------------------------------------------------
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: CIC_Simulink
// Source Path: CIC_HDL_Coder/CIC_Simulink
// Hierarchy Level: 0
// Model version: 1.2
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module CIC_Simulink
          (clk,
           reset,
           clk_enable,
           Input_rsvd,
           ce_out,
           Output_rsvd);


  input   clk;
  input   reset;
  input   clk_enable;
  input   signed [11:0] Input_rsvd;  // sfix12
  output  ce_out;
  output  signed [15:0] Output_rsvd;  // int16


  wire enb_1_4_0;
  wire enb;
  wire enb_1_4_1;
  reg signed [17:0] IntDelay2_out1;  // sfix18
  wire signed [17:0] IntSum2_1;  // sfix18
  wire signed [17:0] IntSum2_out1;  // sfix18
  reg signed [17:0] IntDelay3_out1;  // sfix18
  wire signed [17:0] IntSum3_out1;  // sfix18
  reg signed [17:0] IntDelay4_out1;  // sfix18
  wire signed [17:0] IntSum4_out1;  // sfix18
  reg signed [17:0] Down_Sample_bypass_reg;  // sfix18
  wire signed [17:0] Down_Sample_out1;  // sfix18
  reg signed [17:0] CombDelay6_out1;  // sfix18
  wire signed [17:0] CombSum6_out1;  // sfix18
  reg signed [17:0] CombDelay7_out1;  // sfix18
  wire signed [17:0] CombSum7_out1;  // sfix18
  reg signed [17:0] CombDelay8_out1;  // sfix18
  wire signed [17:0] CombSum8_out1;  // sfix18
  wire signed [17:0] Bit_Shift_out1;  // sfix18
  wire signed [15:0] ConvertOut_out1;  // int16


  CIC_Simulink_tc u_CIC_Simulink_tc (.clk(clk),
                                     .reset(reset),
                                     .clk_enable(clk_enable),
                                     .enb(enb),
                                     .enb_1_4_0(enb_1_4_0),
                                     .enb_1_4_1(enb_1_4_1)
                                     );

  assign IntSum2_1 = {{6{Input_rsvd[11]}}, Input_rsvd};
  assign IntSum2_out1 = IntSum2_1 + IntDelay2_out1;


  always @(posedge clk or negedge reset)
    begin : IntDelay2_process
      if (reset == 1'b0) begin
        IntDelay2_out1 <= 18'sb000000000000000000;
      end
      else begin
        if (enb) begin
          IntDelay2_out1 <= IntSum2_out1;
        end
      end
    end


  assign IntSum3_out1 = IntDelay2_out1 + IntDelay3_out1;


  always @(posedge clk or negedge reset)
    begin : IntDelay3_process
      if (reset == 1'b0) begin
        IntDelay3_out1 <= 18'sb000000000000000000;
      end
      else begin
        if (enb) begin
          IntDelay3_out1 <= IntSum3_out1;
        end
      end
    end


  assign IntSum4_out1 = IntDelay3_out1 + IntDelay4_out1;


  always @(posedge clk or negedge reset)
    begin : IntDelay4_process
      if (reset == 1'b0) begin
        IntDelay4_out1 <= 18'sb000000000000000000;
      end
      else begin
        if (enb) begin
          IntDelay4_out1 <= IntSum4_out1;
        end
      end
    end


  // Down Sample: Downsample by 4, Sample offset 0 
  // Downsample bypass register
  always @(posedge clk or negedge reset)
    begin : Down_Sample_bypass_process
      if (reset == 1'b0) begin
        Down_Sample_bypass_reg <= 18'sb000000000000000000;
      end
      else begin
        if (enb_1_4_1) begin
          Down_Sample_bypass_reg <= IntDelay4_out1;
        end
      end
    end

  assign Down_Sample_out1 = (enb_1_4_1 == 1'b1 ? IntDelay4_out1 :
              Down_Sample_bypass_reg);


  always @(posedge clk or negedge reset)
    begin : CombDelay6_process
      if (reset == 1'b0) begin
        CombDelay6_out1 <= 18'sb000000000000000000;
      end
      else begin
        if (enb_1_4_0) begin
          CombDelay6_out1 <= Down_Sample_out1;
        end
      end
    end


  assign CombSum6_out1 = Down_Sample_out1 - CombDelay6_out1;


  always @(posedge clk or negedge reset)
    begin : CombDelay7_process
      if (reset == 1'b0) begin
        CombDelay7_out1 <= 18'sb000000000000000000;
      end
      else begin
        if (enb_1_4_0) begin
          CombDelay7_out1 <= CombSum6_out1;
        end
      end
    end


  assign CombSum7_out1 = CombSum6_out1 - CombDelay7_out1;


  always @(posedge clk or negedge reset)
    begin : CombDelay8_process
      if (reset == 1'b0) begin
        CombDelay8_out1 <= 18'sb000000000000000000;
      end
      else begin
        if (enb_1_4_0) begin
          CombDelay8_out1 <= CombSum7_out1;
        end
      end
    end


  assign CombSum8_out1 = CombSum7_out1 - CombDelay8_out1;


  assign Bit_Shift_out1 = CombSum8_out1 >> 8'd2;


  assign ConvertOut_out1 = Bit_Shift_out1[15:0];


  assign Output_rsvd = ConvertOut_out1;

  assign ce_out = enb_1_4_1;

endmodule  // CIC_Simulink

