// -------------------------------------------------------------
// 
// 
// Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: CIC_Simulink_tc
// Source Path: CIC_Simulink_tc
// Hierarchy Level: 1
// 
// Master clock enable input: clk_enable
// 
// enb         : identical to clk_enable
// enb_1_4_0   : 4x slower than clk with last phase
// enb_1_4_1   : 4x slower than clk with phase 1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module CIC_Simulink_tc
          (clk,
           reset,
           clk_enable,
           enb,
           enb_1_4_0,
           enb_1_4_1);


  input   clk;
  input   reset;
  input   clk_enable;
  output  enb;
  output  enb_1_4_0;
  output  enb_1_4_1;


  reg [1:0] count4;  // ufix2
  wire comp_0_tmp;
  wire phase_0_tmp;
  reg  phase_0;
  wire enb_1_4_0_1;
  wire comp_1_tmp;
  wire phase_1_tmp;
  reg  phase_1;
  wire enb_1_4_1_1;


  assign enb = clk_enable;

  // Count limited, Unsigned Counter
  //  initial value   = 1
  //  step value      = 1
  //  count to value  = 3
  always @(posedge clk or negedge reset)
    begin : counter_4_process
      if (reset == 1'b0) begin
        count4 <= 2'b01;
      end
      else begin
        if (clk_enable) begin
          count4 <= count4 + 2'b01;
        end
      end
    end



  assign comp_0_tmp = count4 == 2'b11;



  assign phase_0_tmp = comp_0_tmp & clk_enable;



  always @(posedge clk or negedge reset)
    begin : phase_delay_process
      if (reset == 1'b0) begin
        phase_0 <= 1'b0;
      end
      else begin
        if (clk_enable) begin
          phase_0 <= phase_0_tmp;
        end
      end
    end



  assign enb_1_4_0_1 = phase_0 & clk_enable;



  assign enb_1_4_0 = enb_1_4_0_1;

  assign comp_1_tmp = count4 == 2'b00;



  assign phase_1_tmp = comp_1_tmp & clk_enable;



  always @(posedge clk or negedge reset)
    begin : phase_delay_1_process
      if (reset == 1'b0) begin
        phase_1 <= 1'b1;
      end
      else begin
        if (clk_enable) begin
          phase_1 <= phase_1_tmp;
        end
      end
    end



  assign enb_1_4_1_1 = phase_1 & clk_enable;



  assign enb_1_4_1 = enb_1_4_1_1;

endmodule  // CIC_Simulink_tc

